version: '3'

services:
  server:
    build:
      context: ./packages/server
      dockerfile: Dockerfile
    ports:
      - "4001:4001"
    environment:
      - PORT=4001
      - VITE_CLIENT_ID=${VITE_CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - NODE_ENV=production
    volumes:
      - ./.env:/app/.env
    restart: unless-stopped

  client:
    build:
      context: ./packages/client
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - server
    restart: unless-stopped
    
networks:
  default:
    driver: bridge